name: Test

on: [push, pull_request]

jobs:
  build:
    name: Lint Python code
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint
      run: |
        pip install pycodestyle
        pycodestyle .
